### ISSUE TITLE
Non-filesystem based completions

### ISSUE THREAD

**Issue by veged** [cldwalker/lightning#2]
Is it possible to use non-filesystem based completions, e.g. remote svn paths? Can i provide custom command for "item" list generation?

**Comment by cldwalker** [comment]
Lightning works by generating possible completions from file globs. How would you do that with svn paths? 

I'm not sure what you mean by "item" list generation. If items are just files, then [see lightning's generators](http://tagaholic.me/2010/04/08/lightning-speed-for-your-shell.html#generators). If items are not files, lightning isn't the right tool. For non-file completions, I'd recommend your shell's completion system or something like http://github.com/drnic/tabtab.

**Comment by veged** [comment]
yes, tabtab looks more proper

**Comment by veged** [comment]
close
