### ISSUE TITLE
[feature] Use ENV vars in bolt globs

### ISSUE THREAD

**Issue by wuputah** [cldwalker/lightning#3]
Would be nice to be able to use environment variables like $HOME, $rvm_path, $GEM_HOME, $RUBYLIB, etc. Could be extended to have fully dynamic paths, like a glob that searches all of $GEM_PATH (which would need to be split on colon).

Of course, since it's Ruby, these could be strings like #{ENV['HOME']} as an alternative to the shell-style syntax.

**Comment by cldwalker** [comment]
shell var support - https://github.com/cldwalker/lightning/commit/2eaeb0956a7b145b0f1aa97b1e7a90d2f7257b69
dynamic globs using generators - https://github.com/cldwalker/lightning/commit/f6175372de2f1889f2b14fefafb4807945ad6976
Finally :)
